version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: npa-postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/:/var/lib/postgresql/data

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    depends_on:
      - postgresql
    ports:
      - '8001:8001'
