version: '3.8'

services:
  task-manager-api:
    container_name: task-manager-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    ports:
      - '8001:8001'
